name: carcontrol
description: Aplicativo de transporte e controle financeiro
version: 1.0.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.20
  google_maps_flutter:
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0

  firebase_core: ^2.9.1
  cloud_firestore: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
   - assets/images/