name: carcontrol
description: Aplicativo de transporte e controle financeiro
version: 1.0.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.20
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0

  firebase_core: ^2.9.1
  cloud_firestore: ^4.5.1
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.0

  intl: ^0.18.1

  flutter_masked_text2: ^0.9.1
  geocoding: ^2.1.0
  dropdown_button2: ^2.1.3
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
   - assets/images/